name: Build and Package WPF Application

on:
  push:
    branches:
      - release
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Version from Project File
        id: get-version
        shell: bash
        run: echo "version=$(grep -oE '<Version>[^<]+' MyApplication/MyApplication.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x" # Specify the version of .NET you're using

      - name: Publish .NET project
        run: dotnet publish -c Release --self-contained -r win-x64 -o .\publish
        
      - name: Create Velopack Release
              run: |
                dotnet tool install -g vpk
                vpk download github --repoUrl https://github.com/Myname/Myrepo
                vpk pack -u MyUniqueIdentifier -v ${{ steps.get-version.outputs.version }} -p publish
                vpk upload github --repoUrl https://github.com/Myname/Myrepo --publish --releaseName "MyProject ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }}
