name: Build and Package WPF Application

on:
  push:
    branches:
      - release
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x" # Specify the version of .NET you're using

      - name: Publish .NET project
        run: dotnet publish -c Release --self-contained -r win-x64 -o .\publish

      - name: Install
        run: dotnet tool install -g vpk

      - name: Download
        run: vpk download github --repoUrl https://github.com/lmaslovs/WpfVelopack

      - name: Pack
        run: vpk pack --packId WpfVelopack --packVersion 1.0.0 --packDir publish --mainExe WpfVelopack.Wpf.exe --packTitle WpfVelopack --icon .\WpfVelopack.Wpf\Assets\apple.ico

      - name: Create Velopack Release
        run: vpk upload github --repoUrl https://github.com/lmaslovs/WpfVelopack --publish --releaseName "WpfVelopack 1.0.0" --tag v1.0.0 --token ${{ secrets.GITHUB_TOKEN }}
