name: Build and Package WPF Application

on:
  push:
    branches:
      - release
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x" # Specify the version of .NET you're using

      - name: Install Velopack
        run: dotnet tool update -g vpk

      - name: Add Velopack to PATH
        run: echo "$env:USERPROFILE\.dotnet\tools" >> $env:GITHUB_PATH

      - name: Publish .NET project
        run: dotnet publish -c Release --self-contained -r win-x64 -o .\publish

      - name: Package with Velopack
        run: vpk pack --packId WpfVelopack --packVersion 1.0.0 --packDir publish --mainExe WpfVelopack.Wpf.exe --packTitle WpfVelopack --outputDir .\output --icon .\WpfVelopack.Wpf\Assets\apple.ico

      - name: Release
        uses: actions/upload-artifact@v2
        with:
          name: output-artifact
          path: ./output
